### ISSUE TITLE
magc: memory leak depending on grids

### ISSUE THREAD

**Issue by templiert** [SBEMimage/SBEMimage#32]
the computer running SBEMimage here has only 3GB RAM and a memory error reliably occurs after acquisition of about 45 grids (2x2 8k x 6k). There was a Windows dialog complaining about python using too much memory.

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Templier\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Templier\Anaconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Templier\pytools\SBEMimage\src\stack_acquisition.py", line 809, in run
    self.acquire_grid(grid_number)
  File "C:\Templier\pytools\SBEMimage\src\stack_acquisition.py", line 1734, in acquire_grid
    self.acquire_tile(grid_number, tile_number))
  File "C:\Templier\pytools\SBEMimage\src\stack_acquisition.py", line 1598, in acquire_tile
    self.slice_counter))
  File "C:\Templier\pytools\SBEMimage\src\image_inspector.py", line 112, in process_tile
    stddev = np.std(img)
  File "C:\Templier\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 3038, in std
    **kwargs)
  File "C:\Templier\Anaconda3\lib\site-packages\numpy\core\_methods.py", line 140, in _std
    keepdims=keepdims)
  File "C:\Templier\Anaconda3\lib\site-packages\numpy\core\_methods.py", line 117, in _var
    x = asanyarray(arr - arrmean)
MemoryError
```

**Comment by templiert** [comment]
Tentatively [cleaning up some variables](https://github.com/SBEMimage/SBEMimage/commit/6ef27e4946be761e95389304e90e34d4e35fc335) and [adding a workaround](https://github.com/SBEMimage/SBEMimage/commit/bc67e9fcc1159b6f831d0b8e59d78a07bf162365) to stop checking tiles if memory usage is too high.

**Comment by templiert** [comment]
The workaround mentioned above worked and allowed to image twice without interruption 450 grids (2x2, 8k x 6k).

It is not clear whether there was really a serious memory leak, or whether there was only a small memory usage increase that crashed because there is very little memory on the computer (3GB).
