### ISSUE TITLE
Pillow errors with latest version

### ISSUE THREAD

**Issue by K-Meech** [SBEMimage/SBEMimage#82]
On a fresh install of Anaconda + pip install of the requirements on the dev branch, I get the following error:

```
Traceback (most recent call last):
  File "C:\Utilities\SBEMimage\src\SBEMimage.py", line 47, in <module>
    from main_controls_dlg_windows import ConfigDlg
  File "C:\Utilities\SBEMimage\src\main_controls_dlg_windows.py", line 34, in <module>
    from PIL import Image
  File "C:\Users\SEM\anaconda3\lib\site-packages\PIL\Image.py", line 114, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: The specified module could not be found.
```

It's probably something to do with the pillow version.

**Comment by K-Meech** [comment]
Uninstalling pillow and pip installing it works. Something must be different with the version that comes directly with Anaconda.

**Comment by K-Meech** [comment]
This seems to work now - so I'll close
